# =============================================================================
# Dockerfile
# Phase 5 — Cloud Run Deployment
# NTRO Non-IoC Network Flow Anomaly Detection Project
#
# Multi-stage build:
#   Stage 1 (builder) — install Python deps + generate Prisma client
#   Stage 2 (runtime) — lean final image with only what Cloud Run needs
#
# Build
# -----
#   docker build -t ntro-api .
#
# Run locally
# -----------
#   docker run -p 8000:8000 \
#     -e DATABASE_URL="postgresql://..." \
#     -e REDIS_URL="redis://..." \
#     -v $(pwd)/artifacts:/app/artifacts \
#     ntro-api
#
# Deploy to Cloud Run
# -------------------
#   gcloud run deploy ntro-api \
#     --image gcr.io/<PROJECT_ID>/ntro-api \
#     --platform managed --region us-central1 \
#     --set-env-vars DATABASE_URL=...,REDIS_URL=... \
#     --allow-unauthenticated
# =============================================================================


# -----------------------------------------------------------------------------
# Stage 1: Builder — install Python dependencies and generate Prisma client
# -----------------------------------------------------------------------------
FROM python:3.11-slim AS builder

# Install system dependencies required by:
#   - psycopg2-binary / libpq (Prisma → Neon PostgreSQL)
#   - curl (Prisma CLI download)
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
        curl \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# ---- Copy dependency manifests first (layer-caching optimisation) ----------
COPY requirements.txt .

# ---- Install Python packages into /build/venv ------------------------------
# Use PyTorch CPU-only wheels to keep the image lean (no CUDA overhead).
# The --extra-index-url provides the CPU-only PyTorch wheel index.
RUN python -m venv /build/venv && \
    /build/venv/bin/pip install --upgrade pip setuptools wheel && \
    /build/venv/bin/pip install \
        --extra-index-url https://download.pytorch.org/whl/cpu \
        --no-cache-dir \
        -r requirements.txt

# ---- Copy Prisma schema and generate the Python client ---------------------
COPY schema.prisma .
RUN /build/venv/bin/prisma generate --schema=schema.prisma


# -----------------------------------------------------------------------------
# Stage 2: Runtime — lean production image
# -----------------------------------------------------------------------------
FROM python:3.11-slim AS runtime

# Install only the runtime system libraries (no build tools)
RUN apt-get update && apt-get install -y --no-install-recommends \
        libpq5 \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user for Cloud Run security best-practices
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser

WORKDIR /app

# ---- Copy the virtual environment from the builder stage -------------------
COPY --from=builder /build/venv /app/venv

# ---- Copy application source files -----------------------------------------
COPY data_loader.py \
     preprocessing.py \
     model.py \
     inference.py \
     risk_engine.py \
     database.py \
     main.py \
     schema.prisma \
     ./

# ---- Copy ML artifacts (scaler + autoencoder weights + metadata) -----------
# These are generated by running `python train.py` locally before building.
# If you prefer to mount them at runtime, remove this COPY and use a volume.
COPY artifacts/ ./artifacts/

# ---- Set environment variables with sensible defaults ----------------------
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PATH="/app/venv/bin:$PATH" \
    ARTIFACTS_DIR="/app/artifacts" \
    PORT=8000

# Cloud Run injects PORT; uvicorn reads it via the CMD below.
EXPOSE 8000

# Switch to non-root user
USER appuser

# ---- Health check -----------------------------------------------------------
HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:${PORT}/health')"

# ---- Entrypoint -------------------------------------------------------------
# Cloud Run sets $PORT (default 8080). We default to 8000 locally.
# --workers 1 is deliberate: Cloud Run scales horizontally via instances,
# not vertically via multiple uvicorn workers per container.
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT} --workers 1 --log-level info"]
